// src/app/layout.tsx
import type { Metadata } from 'next'
import { Roboto, Roboto_Mono } from 'next/font/google'
import './globals.css'
import SeoProvider from './SeoProvider'

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
	weight: '900',
})

const robotoMono = Roboto_Mono({
	variable: '--font-roboto-mono',
	subsets: ['latin'],
	weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en'>
			<body
				className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
				<SeoProvider />
				{children}
			</body>
		</html>
	)
}
