import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Form from '../components/Form'
import Hero from '../components/Hero'
import Portfolio from '../components/Portfolio'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Akshay Benny</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css?family=Poppins'
          rel='stylesheet'
        />
      </Head>

      <main className='bg-black min-h-screen font-Poppins'>
        <Hero />
        <Portfolio />
        <About />
        <Form />
      </main>
    </div>
  )
}
